---
name: 'mapbuilder'
author: 'vatger-nav'
description: 'Builder for GRPlugin and Topsky maps'
inputs:
  target-path:
    description: 'Target directory relative to repository root'
    required: True
    default: '.'
  source-path:
    description: 'Source directory with mapbuilder.toml relative to repository root'
    required: True
    default: 'mapdata'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/vatger-nav/mapbuilder:main'
  args:
    - '--debug'
    - '-s'
    - '/github/workspace/${{ inputs.source-path }}'
    - '/github/workspace/${{ inputs.target-path }}'
branding:
  icon: 'map'
  color: 'green'
