---
name: 'mapbuilder'
author: 'vatger-nav'
description: 'Builder for GRPlugin and Topsky maps'
runs:
  using: 'docker'
  image: 'docker://ghcr.io/vatger-nav/mapbuilder:main'
  args:
    - '--debug'
    - '-s'
    - '/github/workspace/mapdata'
    - '/github/workspace'
branding:
  icon: 'map'
  color: 'green'
