name: Build

on:
  push:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Install poetry
        run: |
          pip install poetry
      - name: Build
        run: |
          poetry install
          poetry run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Windows
          path: dist/mapbuilder.exe
